Drop almost all 'None' defaults
Unless used with MelOptStructs, these just break the BP:

mod_io.py  367 packSub: <bash.brec.mod_io.ModWriter object at 0x16FDA550>: Failed packing: CRDT, H2sfB3sI, (0, '\x00\x00', 0, 0, '\x00\x00\x00', None)
mod_structs.py  106 dumpData: Error dumping data:
Traceback (most recent call last):
  File "bash\brec\mod_structs.py", line 104, in dumpData
    element.dumpData(record,out)
  File "bash\brec\advanced_elements.py", line 840, in dumpData
    self._get_element_from_record(record).dumpData(record, out)
  File "bash\brec\basic_elements.py", line 564, in dumpData
    out.packSub(self.subType, self.struct_format, *values)
  File "bash\brec\mod_io.py", line 354, in packSub
    if values: data = struct_pack(data, *values)
error: cannot convert argument to integer

Some of these were being used with opt structs where the structs should
have just been required, some were completely pointless. Surprised this
didn't blow up early to be honest...

Left comments on the ones that actually have a purpose.
Semi-PEP8'd and prefixed the things I touched, as per usual.

brec.MelRef3D, brec.MelXlod

Had to touch them anyways, so decided to get rid of the duplication
while I was at it.

Fixup for Skyrim's MreAlch ENIT

Again, happily mangling fids during merging.

TES4, FO3, FNV: Minor fixups

Went ahead and dropped the XGLB that does not exist in FO3/FNV, as the
comment indicated. Also used MelReadOnly for SNDD in TES4, same as in
FO3/FNV (could have sworn I already did that at some point...).